services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./flask-backend/Dockerfile
    dockerContext: ./flask-backend

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./perfume-front-nextjs/Dockerfile
    dockerContext: ./perfume-front-nextjs
